#### Best Pratices 

1. Preprocessing And Cleaning 
2. Train-Test Split
3. BOW, TFIDF, Word2Vec
4. Train ML algo

In [18]:
### Load the dataset
import pandas as pd
data = pd.read_csv(r"D:\Krish_Naik\Python\NLP For ML\Kindle Review\all_kindle_review .csv")
data.head()


,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000


In [19]:
data =data[['reviewText','rating']]
data.head()

,reviewText,rating
0,"Jace Rankin may be short, but he's nothing to ...",3
1,Great short read. I didn't want to put it dow...,5
2,I'll start by saying this is the first of four...,3
3,Aggie is Angela Lansbury who carries pocketboo...,3
4,I did not expect this type of book to be in li...,4


In [20]:
data.shape

(12000, 2)

In [21]:
### Missing values
data.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [22]:
data['rating'].unique()

array([3, 5, 4, 2, 1])

In [23]:
data['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [24]:
#### 1. Preprocessing and cleaning
## Postive revies is 1 and negative review is 0
data['rating'] =data['rating'].apply(lambda x:0 if x<3 else 1)

In [25]:
data['rating'].unique()

array([1, 0])

In [26]:
data['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [27]:
### Step 1 -- Lower all the cases
data['reviewText'] =data['reviewText'].str.lower()

In [28]:
data.head()

,reviewText,rating
0,"jace rankin may be short, but he's nothing to ...",1
1,great short read. i didn't want to put it dow...,1
2,i'll start by saying this is the first of four...,1
3,aggie is angela lansbury who carries pocketboo...,1
4,i did not expect this type of book to be in li...,1


In [29]:
import re 
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ranje\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [30]:
from bs4 import BeautifulSoup

In [ ]:
### Step 2 -- Clean the data -- 
# Removing special characters
data['reviewText'] =data['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 0-9]+','',x))
# Removing the stipwords
data['reviewText'] =data['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
# Remove url
data['reviewText'] =data['reviewText'].apply(lambda x:re.sub(r'(http|https|ftp|://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?())','',str(x)))
# Remove html tags
data['reviewText'] =data['reviewText'].apply(lambda x: BeautifulSoup(x,'lxml').get_text())
# Remove Any additional spaces
data['reviewText'] =data['reviewText'].apply(lambda x:" ".join(x.split()))

In [32]:
data.head()

,reviewText,rating
0,jace rankin may short hes nothing mess man hau...,1
1,great short read didnt want put read one sitti...,1
2,ill start saying first four books wasnt expect...,1
3,aggie angela lansbury carries pocketbooks inst...,1
4,expect type book library pleased find price right,1


In [33]:
### Lemmatizer
from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()

In [34]:
def lemmatize_words(text):
    return " ".join([lemma.lemmatize(word) for word in text.split()])

In [35]:
data['reviewText'] =data['reviewText'].apply(lambda x:lemmatize_words(x))

In [36]:
data.head()

,reviewText,rating
0,jace rankin may short he nothing mess man haul...,1
1,great short read didnt want put read one sitti...,1
2,ill start saying first four book wasnt expecti...,1
3,aggie angela lansbury carry pocketbook instead...,1
4,expect type book library pleased find price right,1


In [37]:
### Train-Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data['reviewText'],data['rating'],
                                               test_size=0.20)

In [38]:
X_train.shape

(9600,)

In [40]:
y_train.shape

(9600,)

In [41]:
X_test.shape

(2400,)

In [42]:
y_test.shape

(2400,)

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer()
X_train_bow = bow.fit_transform(X_train).toarray()
X_test_bow =bow.transform(X_test).toarray()

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf =tfidf.transform(X_test).toarray()

In [47]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(9600, 37445))

In [48]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow = GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf = GaussianNB().fit(X_train_tfidf,y_train)

In [49]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [50]:
y_pred_bow = nb_model_bow.predict(X_test_bow)

In [51]:
y_pred_tfidf = nb_model_bow.predict(X_test_tfidf)

In [53]:
confusion_matrix(y_test,y_pred_bow)

array([[507, 286],
       [730, 877]])

In [52]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.5766666666666667


In [56]:
confusion_matrix(y_test,y_pred_tfidf)

array([[497, 296],
       [726, 881]])

In [54]:
print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TFIDF accuracy:  0.5741666666666667


In [57]:
from gensim.models import Word2Vec
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [58]:
X_train_tokens = [text.split() for text in X_train]
X_test_tokens = [text.split() for text in X_test]

In [59]:
w2v_model = Word2Vec(
    sentences=X_train_tokens,
    vector_size=200,
    window=10,
    min_count=1,
    workers=4
)

In [60]:
def avg_word2vec(words, model, vector_size):
    vec = np.zeros(vector_size)
    count = 0
    
    for word in words:
        if word in model.wv:
            vec += model.wv[word]
            count += 1
    
    if count != 0:
        vec = vec / count
        
    return vec

In [61]:
X_train_w2v = np.array([avg_word2vec(words, w2v_model, 200) for words in X_train_tokens])
X_test_w2v = np.array([avg_word2vec(words, w2v_model, 200) for words in X_test_tokens])

In [62]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_w2v, y_train)

y_pred = model.predict(X_test_w2v)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7583333333333333
[[ 400  393]
 [ 187 1420]]
              precision    recall  f1-score   support

           0       0.68      0.50      0.58       793
           1       0.78      0.88      0.83      1607

    accuracy                           0.76      2400
   macro avg       0.73      0.69      0.71      2400
weighted avg       0.75      0.76      0.75      2400



In [63]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100)
model.fit(X_train_w2v, y_train)

y_pred = model.predict(X_test_w2v)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7670833333333333


In [64]:
from xgboost import XGBClassifier

model = XGBClassifier()
model.fit(X_train_w2v, y_train)

y_pred = model.predict(X_test_w2v)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.745


In [65]:
from sklearn.ensemble import RandomForestClassifier
nb_model_bow = RandomForestClassifier().fit(X_train_bow,y_train)
nb_model_tfidf = RandomForestClassifier().fit(X_train_tfidf,y_train)

In [66]:
y_pred_bow = nb_model_bow.predict(X_test_bow)

In [67]:
y_pred_tfidf = nb_model_bow.predict(X_test_tfidf)

In [68]:
confusion_matrix(y_test,y_pred_bow)

array([[ 367,  426],
       [  48, 1559]])

In [69]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.8025


In [71]:
print("TF-IDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TF-IDF accuracy:  0.6708333333333333


In [72]:
from sklearn.linear_model import LogisticRegression
nb_model_bow = LogisticRegression().fit(X_train_bow,y_train)
nb_model_tfidf = LogisticRegression().fit(X_train_tfidf,y_train)

In [73]:
y_pred_bow = nb_model_bow.predict(X_test_bow)

In [74]:
y_pred_tfidf = nb_model_bow.predict(X_test_tfidf)

In [75]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.8375


In [76]:
print("TF-IDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TF-IDF accuracy:  0.8225


In [77]:
from xgboost import XGBClassifier
nb_model_bow = XGBClassifier().fit(X_train_bow,y_train)
nb_model_tfidf = XGBClassifier().fit(X_train_tfidf,y_train)

In [78]:
y_pred_bow = nb_model_bow.predict(X_test_bow)

In [79]:
y_pred_tfidf = nb_model_bow.predict(X_test_tfidf)

In [80]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.8166666666666667


In [81]:
print("TF-IDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TF-IDF accuracy:  0.6695833333333333
