In [2]:
import gensim 
from gensim.models import word2vec, keyedvectors

In [3]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
vec_king=wv['king']

In [4]:
vec_king.shape

(300,)

In [5]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [6]:
import pandas as pd
messages = pd.read_csv(r"D:\Krish_Naik\Python\NLP For ML\uci_sms_spam_mock.csv",sep=',')

In [7]:
messages

,label,message
0,ham,Please send the report by evening.
1,ham,Can you check this file?
2,ham,Can you check this file?
3,ham,Call me when you're free.
4,ham,Let's have lunch today.
...,...,...
5567,ham,"Hey, are we meeting tomorrow?"
5568,ham,Can you check this file?
5569,spam,Congratulations! You have won a free ticket. C...
5570,spam,Congratulations! You have won a free ticket. C...


In [8]:
import re 
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ranje\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [9]:
from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()


In [10]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review = review.split()
    review = [
        lemma.lemmatize(word) 
        for word in review
        ]
    review = ' '.join(review)
    corpus.append(review)

In [11]:
corpus

['Please send the report by evening',
 'Can you check this file',
 'Can you check this file',
 'Call me when you re free',
 'Let s have lunch today',
 'Can you check this file',
 'Please send the report by evening',
 'You have been selected for a reward',
 'Win cash prize now',
 'Congratulations You have won a free ticket Call now',
 'You have been selected for a reward',
 'Call me when you re free',
 'Claim your free voucher today',
 'Can you check this file',
 'Win cash prize now',
 'Exclusive offer just for you Click now',
 'Please send the report by evening',
 'Let s have lunch today',
 'Win cash prize now',
 'Hey are we meeting tomorrow',
 'Congratulations You have won a free ticket Call now',
 'You have been selected for a reward',
 'Call me when you re free',
 'Let s have lunch today',
 'Please send the report by evening',
 'Let s have lunch today',
 'Claim your free voucher today',
 'Congratulations You have won a free ticket Call now',
 'Let s have lunch today',
 'Claim your f

In [12]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess ### Convert a document into a list of lowercase tokens, ignoring tokens that are too short or too long

In [13]:
words =[]
for sent in corpus:
    sent_token =sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [14]:
words

[['please', 'send', 'the', 'report', 'by', 'evening'],
 ['can', 'you', 'check', 'this', 'file'],
 ['can', 'you', 'check', 'this', 'file'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['let', 'have', 'lunch', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['win', 'cash', 'prize', 'now'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticket', 'call', 'now'],
 ['you', 'have', 'been', 'selected', 'for', 'reward'],
 ['call', 'me', 'when', 'you', 're', 'free'],
 ['claim', 'your', 'free', 'voucher', 'today'],
 ['can', 'you', 'check', 'this', 'file'],
 ['win', 'cash', 'prize', 'now'],
 ['exclusive', 'offer', 'just', 'for', 'you', 'click', 'now'],
 ['please', 'send', 'the', 'report', 'by', 'evening'],
 ['let', 'have', 'lunch', 'today'],
 ['win', 'cash', 'prize', 'now'],
 ['hey', 'are', 'we', 'meeting', 'tomorrow'],
 ['congratulations', 'you', 'have', 'won', 'free', 'ticke

In [15]:
import gensim

In [16]:
model=gensim.models.Word2Vec(words)

In [17]:
## Get all the vocab
model.wv.index_to_key

['you',
 'have',
 'now',
 'free',
 'today',
 'call',
 'for',
 'lunch',
 'let',
 'file',
 'this',
 'check',
 'can',
 'voucher',
 'your',
 'claim',
 'prize',
 'cash',
 'win',
 'ticket',
 'won',
 'congratulations',
 'click',
 'just',
 'offer',
 'exclusive',
 'tomorrow',
 'meeting',
 'we',
 'are',
 'hey',
 're',
 'when',
 'me',
 'reward',
 'selected',
 'been',
 'evening',
 'by',
 'report',
 'the',
 'send',
 'please']

In [18]:
model.corpus_count

5572

In [19]:
model.epochs

5

In [20]:
model.wv.similar_by_word('report')

[('send', 0.9984312653541565),
 ('evening', 0.9980818629264832),
 ('by', 0.9979560971260071),
 ('please', 0.9976500272750854),
 ('the', 0.9976310729980469),
 ('we', 0.4917351007461548),
 ('meeting', 0.48544904589653015),
 ('hey', 0.4834009110927582),
 ('tomorrow', 0.4785919785499573),
 ('are', 0.4735286235809326)]

In [21]:
model.wv['report'].shape

(100,)

In [22]:
words[0]

['please', 'send', 'the', 'report', 'by', 'evening']

In [23]:
import numpy as np

In [24]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent =[word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
    

In [25]:
from tqdm import tqdm

In [26]:
# Apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

100%|██████████| 5572/5572 [00:00<00:00, 64510.48it/s]


In [27]:
X

[array([-0.25461656, -0.07331955, -0.4633806 , -0.63977   ,  0.07634231,
        -0.42980227,  0.09434512, -0.09487925,  0.12828323, -0.2729636 ,
         0.12713458, -0.24168712, -0.4633734 ,  0.22808085, -0.16224827,
        -0.5752127 ,  0.33512673,  0.20968227,  0.07804129, -0.08187891,
         0.24554731,  0.12398487,  0.6309499 , -0.45347503,  0.6076395 ,
         0.20151077,  0.10384661, -0.03536486, -0.332904  , -0.00766904,
         0.4332116 , -0.03193435,  0.28335065, -0.6970453 , -0.06206281,
         0.3279471 , -0.28644636,  0.14145671, -0.23801677, -0.36956057,
        -0.2235082 , -0.10219637,  0.15998487, -0.32705116, -0.05291256,
        -0.5639821 ,  0.01560055, -0.4133457 ,  0.2543101 ,  0.35088634,
         0.28881156,  0.23814376,  0.1677181 ,  0.3033894 , -0.19244462,
        -0.01644522,  0.24194169, -0.10231251, -0.639069  , -0.04979542,
         0.24953987, -0.28505278,  0.21318066,  0.23450786, -0.20303805,
         0.34603444, -0.73242664, -0.12470893, -0.7

In [28]:
len(X)

5572

In [29]:
X_new = np.array(X)

In [30]:
X_new

array([[-0.25461656, -0.07331955, -0.4633806 , ..., -0.4428594 ,
        -0.39611006, -0.27724633],
       [ 0.1477429 , -0.07057855,  0.17113039, ..., -0.13043614,
         0.20622274,  0.01826736],
       [ 0.1477429 , -0.07057855,  0.17113039, ..., -0.13043614,
         0.20622274,  0.01826736],
       ...,
       [-0.01926546,  0.19884826,  0.17584701, ..., -0.09257931,
         0.13106053,  0.0085611 ],
       [-0.01926546,  0.19884826,  0.17584701, ..., -0.09257931,
         0.13106053,  0.0085611 ],
       [ 0.21624763,  0.06982184,  0.27139404, ..., -0.0985458 ,
         0.11773439,  0.25103137]], shape=(5572, 100), dtype=float32)

In [31]:
X_new.shape

(5572, 100)

In [37]:
X_new[0].reshape(1,-1).shape

(1, 100)

In [41]:
df = pd.DataFrame()
rows =[]
for i in range(0,len(X_new)):
    rows.append(pd.DataFrame(X_new[i].reshape(1,-1)))
df =pd.concat(rows,ignore_index=True)

In [42]:
df.shape

(5572, 100)

In [43]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.254617,-0.073320,-0.463381,-0.639770,0.076342,-0.429802,0.094345,-0.094879,0.128283,-0.272964,...,0.239024,-0.127157,0.180486,-0.531697,-0.047999,0.133609,-0.182787,-0.442859,-0.396110,-0.277246
1,0.147743,-0.070579,0.171130,0.012348,-0.193223,-0.403339,0.019342,0.638998,-0.110745,-0.542301,...,0.166411,0.030243,0.084340,-0.054088,0.452143,-0.149876,-0.014200,-0.130436,0.206223,0.018267
2,0.147743,-0.070579,0.171130,0.012348,-0.193223,-0.403339,0.019342,0.638998,-0.110745,-0.542301,...,0.166411,0.030243,0.084340,-0.054088,0.452143,-0.149876,-0.014200,-0.130436,0.206223,0.018267
3,-0.095190,0.058350,0.052204,0.208025,-0.264500,-0.285792,0.062047,0.479168,0.044642,-0.603174,...,0.031845,0.043011,0.002815,-0.279587,0.350769,-0.053518,0.013912,-0.211485,0.218844,-0.143524
4,-0.253883,0.297177,0.010476,0.220981,-0.069510,-0.136869,0.170323,0.154026,-0.112700,-0.200240,...,0.059671,0.065007,0.101454,-0.198329,0.143093,0.052201,0.232507,0.046923,-0.104872,0.105902


In [33]:
### Dependent Features
## O/P Features
y =pd.get_dummies(messages['label'])
y=y.iloc[:,0].values
y = messages['label'].map({'ham':0,'spam':1}).values

In [44]:
y

array([0, 0, 0, ..., 1, 1, 1], shape=(5572,))

In [45]:
y.shape

(5572,)

In [46]:
## Independent Feature
X =df

In [47]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [49]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
3988,0.147743,-0.070579,0.171130,0.012348,-0.193223,-0.403339,0.019342,0.638998,-0.110745,-0.542301,...,0.166411,0.030243,0.084340,-0.054088,0.452143,-0.149876,-0.014200,-0.130436,0.206223,0.018267
3922,-0.254617,-0.073320,-0.463381,-0.639770,0.076342,-0.429802,0.094345,-0.094879,0.128283,-0.272964,...,0.239024,-0.127157,0.180486,-0.531697,-0.047999,0.133609,-0.182787,-0.442859,-0.396110,-0.277246
4021,-0.114956,-0.038377,-0.414197,0.342888,0.222253,0.107734,0.451521,-0.043613,-0.191206,0.253215,...,0.265863,0.226658,0.165335,-0.427779,0.254743,0.048516,-0.022255,-0.368909,-0.073423,0.018925
953,-0.019265,0.198848,0.175847,0.329571,-0.263679,-0.192893,0.151569,0.537639,-0.095739,-0.533826,...,0.044779,0.029397,0.064885,-0.115709,0.351501,-0.009429,0.067490,-0.092579,0.131061,0.008561
681,-0.019265,0.198848,0.175847,0.329571,-0.263679,-0.192893,0.151569,0.537639,-0.095739,-0.533826,...,0.044779,0.029397,0.064885,-0.115709,0.351501,-0.009429,0.067490,-0.092579,0.131061,0.008561


In [51]:
y_train

array([0, 0, 0, ..., 1, 0, 0], shape=(4457,))

In [52]:
from sklearn.ensemble import RandomForestClassifier
classifier =RandomForestClassifier()

In [54]:
X.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [53]:
classifier.fit(X_train,y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [55]:
y_pred = classifier.predict(X_test)

In [56]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

1.0


In [57]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       570
           1       1.00      1.00      1.00       545

    accuracy                           1.00      1115
   macro avg       1.00      1.00      1.00      1115
weighted avg       1.00      1.00      1.00      1115

