In [1]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 46.0 MB/s eta 0:00:00


In [2]:
import gensim

In [3]:
from gensim.models import Word2Vec,KeyedVectors

In [4]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king =wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [6]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [7]:
vec_king.shape

(300,)

In [11]:
wv['Relationships']

array([ 0.04248047, -0.16503906, -0.20996094,  0.18359375, -0.18164062,
       -0.02355957,  0.02075195,  0.0625    , -0.11279297,  0.19140625,
        0.07275391,  0.23339844, -0.08544922,  0.44921875, -0.10498047,
        0.18945312,  0.40625   ,  0.3984375 ,  0.27148438,  0.04980469,
        0.22167969, -0.05541992,  0.54296875,  0.01489258, -0.09033203,
       -0.09277344, -0.18164062,  0.25195312,  0.12451172, -0.40625   ,
       -0.07324219, -0.18261719,  0.04907227, -0.41992188,  0.12353516,
        0.01940918, -0.11279297,  0.19726562, -0.25976562, -0.15820312,
       -0.1640625 ,  0.12304688, -0.35351562,  0.14746094, -0.13964844,
       -0.38476562,  0.359375  ,  0.06738281, -0.29101562,  0.16015625,
       -0.49414062,  0.19238281, -0.24707031,  0.2890625 ,  0.19628906,
        0.41601562, -0.16015625, -0.01403809, -0.21679688,  0.1328125 ,
        0.03662109,  0.24902344,  0.07617188,  0.08056641, -0.38867188,
        0.078125  ,  0.1328125 ,  0.0559082 ,  0.16894531, -0.46

In [13]:
wv.most_similar('Love')

[('Song_Sara_Bareilles', 0.611312985420227),
 ('Adore_Mi_Amore', 0.6027418375015259),
 ("'ve_Chosen_Darkness", 0.6016384959220886),
 ('Most_Embarrassing_Gaffe', 0.5969030261039734),
 ('Rex_Walheim_Stanley', 0.5837333798408508),
 ('Paris_xoxo', 0.5787387490272522),
 ('Talkin_About', 0.5585812926292419),
 ('Actor_comedian_Faizon', 0.5371077060699463),
 ('Lover', 0.5354419946670532),
 ('Beyoncé_Crazy', 0.5344488620758057)]

In [15]:
wv['books']

array([ 9.76562500e-02,  2.29492188e-01, -1.05590820e-02,  2.59765625e-01,
        1.99218750e-01, -4.39453125e-02, -1.62353516e-02,  2.26562500e-01,
        2.12402344e-02, -3.66210938e-02,  2.48046875e-01, -1.98242188e-01,
        9.27734375e-02,  1.73828125e-01, -1.26953125e-01,  3.27148438e-02,
       -3.66210938e-03, -1.37329102e-03,  1.92382812e-01, -4.15039062e-02,
        2.32421875e-01, -1.57226562e-01,  7.66601562e-02, -1.99218750e-01,
       -1.74804688e-01, -1.68945312e-01, -2.08984375e-01,  1.31835938e-02,
       -1.07421875e-01, -3.24218750e-01, -1.15234375e-01, -2.49023438e-02,
       -1.77734375e-01,  2.08007812e-01,  2.22656250e-01,  1.66015625e-01,
       -8.23974609e-03, -1.16699219e-01,  1.12304688e-01,  4.95605469e-02,
       -6.25000000e-02,  3.22265625e-02,  1.57226562e-01,  1.49414062e-01,
        1.03759766e-02,  1.21582031e-01,  5.12695312e-02, -1.25976562e-01,
       -1.84570312e-01, -1.77734375e-01, -1.84570312e-01, -4.32128906e-02,
        1.44653320e-02, -

In [24]:
wv.most_similar('Sapiens')

[('Harcase', 0.5582461357116699),
 ('RapidSure', 0.4946799576282501),
 ('Nasdaq_SPNS', 0.46052467823028564),
 ('Sapiens_International', 0.4549875855445862),
 ('TASE_FORT', 0.44773727655410767),
 ('UniRisX', 0.44368425011634827),
 ('AgencyPort', 0.4409078061580658),
 ('RapidSure_Policy_Administration', 0.4395613968372345),
 ('DSTi', 0.4390014410018921),
 ('SOLCORP', 0.43493562936782837)]

In [39]:
wv.similarity("Hockey","Sport")

np.float32(0.35183594)

In [40]:
vec=wv['King']-wv['man']+wv['woman']

In [41]:
vec

array([-8.65173340e-02, -1.91772461e-01, -2.19238281e-01,  1.03515625e-01,
        1.40625000e-01, -7.15026855e-02,  1.14624023e-01,  6.80541992e-02,
        1.88964844e-01,  1.20368958e-01, -2.63671875e-01,  6.83593750e-02,
        4.24804688e-02, -6.73828125e-02, -5.29785156e-02, -7.05566406e-02,
       -2.01171875e-01,  5.37109375e-03, -4.58984375e-02,  3.23974609e-01,
        1.19750977e-01,  9.22088623e-02, -2.00195312e-02, -2.23632812e-01,
        2.38037109e-02,  1.07421875e-02, -3.38867188e-01, -1.71875000e-01,
        1.22070312e-01, -1.00097656e-01, -5.68847656e-02, -2.33276367e-01,
       -2.33886719e-01,  8.91113281e-03, -2.08007812e-01, -6.73828125e-02,
        2.99804688e-01,  8.52661133e-02, -4.70214844e-01, -1.45874023e-01,
       -2.84912109e-01, -2.98095703e-01, -1.14257812e-01,  2.05505371e-01,
       -1.51367188e-02,  1.03271484e-01,  1.55273438e-01, -1.09863281e-01,
        1.77001953e-02, -2.53906250e-02,  1.57226562e-01, -8.50601196e-02,
       -1.53564453e-01,  

In [42]:
wv.most_similar([vec])

[('King', 0.7780153751373291),
 ('Queen', 0.55495285987854),
 ('Oprah_BFF_Gayle', 0.4718775153160095),
 ('Princess', 0.464548259973526),
 ('Geoffrey_Rush_Exit', 0.46232518553733826),
 ('K._Letourneau', 0.45581626892089844),
 ('Alveda_C.', 0.4519498348236084),
 ('L._Bonauto', 0.45188432931900024),
 ('Yvonne_Stickney', 0.45108562707901),
 ('Mecklenburg_Strelitz', 0.4499910771846771)]