In [1]:
### Data Analysis with Pythpn

!pip install numpy


In [4]:
## Creating ndarray 
import numpy as np

arr1 = np.array([1,2,3,4,5])

print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## Creaating a 2d array  --> Convert 1d array from 2d array by using reshape...

arr2 = np.array([1,2,3,4,5])

arr2.reshape(1,5)  # 1 row and 5 cols


array([[1, 2, 3, 4, 5]])

In [8]:
# 2D array 

arr3 = np.array([[1,2,4,6,7,8],[2,4,5,7,8,9]])
arr3.shape

(2, 6)

In [9]:
### Perform operations by using in- bulit function 

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creating array using default values

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Creating array using default values

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
## Identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
ar1 = np.array([[1,2,3],[4,5,6]])

print("Array :\n ",ar1) # return arrary
print("Shape of Array is :",ar1.shape) # Return shape of array
print("Number of dimension in Array: ",ar1.ndim)
print("The Size of the array is :", ar1.size)
print("Datatype is :", ar1.dtype)
print("Item Size in bytes :", ar1.itemsize)

Array :
  [[1 2 3]
 [4 5 6]]
Shape of Array is : (2, 3)
Number of dimension in Array:  2
The Size of the array is : 6
Datatype is : int64
Item Size in bytes : 8


In [31]:
# Vectorization operations

Ar1 = np.array([1,3,5,7,9])
Ar2 = np.array([2,4,6,8,10])

# Addition 
print("Addition of array is :", Ar1+Ar2)

# Substration
print("Substration of array is :", Ar1-Ar2)

# Multiplication
print("Multiplication of array is :", Ar1*Ar2)

# Division
print("Division of array is :", Ar1/Ar2)


Addition of array is : [ 3  7 11 15 19]
Substration of array is : [-1 -1 -1 -1 -1]
Multiplication of array is : [ 2 12 30 56 90]
Division of array is : [0.5        0.75       0.83333333 0.875      0.9       ]


In [32]:
### Universal Function 

arr = np.array([2,3,4,5,6])

print(np.sqrt(arr)) # Square root

print(np.exp(arr)) # Exponential 

print(np.sin(arr)) # Sin value

print(np.log(arr)) # Log value

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [36]:
### Array Slicing and Indexing

arr1 = np.array([[1,2,3,4,5],[2,4,6,8,10],[1,3,5,7,9]])

print("Array :\n",arr1)

np.shape(arr1)

Array :
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 1  3  5  7  9]]


(3, 5)

In [ ]:
#Return last elements in 2nd and 3rd row
arr1[1:,3:]


array([[ 8, 10],
       [ 7,  9]])

In [ ]:
# Return first 2 rows in array
arr1[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [43]:
arr1[0:2,2:]

array([[ 3,  4,  5],
       [ 6,  8, 10]])

In [44]:
arr1[0:3,2:4]

array([[3, 4],
       [6, 8],
       [5, 7]])

In [45]:
### Modify array elements

arr1[0][0] =100
print(arr1)

[[100   2   3   4   5]
 [  2   4   6   8  10]
 [  1   3   5   7   9]]


In [51]:
## Stastistical Concept --> Normalization
## To have a mean is 0 and standard Deviation is 1

a = np.array([1, 2, 3, 4])
print(np.sum(a))        # 10
mean = np.mean(a)      # 2.5)
std_dev=np.std(a)     # Standard deviation
print(np.max(a), np.min(a))
print(np.median(a))
print(np.percentile(a, 75))

normalization = (a - mean)/std_dev

print(normalization)

10
4 1
2.5
3.25
[-1.34164079 -0.4472136   0.4472136   1.34164079]


In [58]:
data = np.array([1, 2, 3, 4])

# Mean
print("Mean: ",np.mean(data))

#Median
print("Median: ",np.median(data))

# Standard Deviation
print("Standard Deviation: ",np.std(data))

# Variance 
print("Variance: ",np.var(data))

Mean:  2.5
Median:  2.5
Standard Deviation:  1.118033988749895
Variance:  1.25


In [61]:
#### Logical Operations

data = np.arange(10)
data[data>5]


array([6, 7, 8, 9])