In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### Sentences
sent =[
    'I love my dog',
    'I love my cat',
    'the dog is my best friend',
    'I am a good developer',
    'understanding embedding layer',
    'you can use embedding layer in deep learning'
]

In [3]:
sent

['I love my dog',
 'I love my cat',
 'the dog is my best friend',
 'I am a good developer',
 'understanding embedding layer',
 'you can use embedding layer in deep learning']

In [4]:
### Defining Vocabulary Size
voc_size = 10000


In [5]:
### One hot Representation3
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr


[[1388, 6719, 6005, 1744],
 [1388, 6719, 6005, 3835],
 [3513, 1744, 9661, 6005, 9682, 4659],
 [1388, 1604, 5026, 7696, 5895],
 [2876, 3682, 5639],
 [9637, 9352, 3422, 3682, 5639, 1294, 4798, 4959]]

In [6]:
### Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences 
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [10]:
set_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=set_length)
print(embedded_docs)

[[   0    0    0    0 1388 6719 6005 1744]
 [   0    0    0    0 1388 6719 6005 3835]
 [   0    0 3513 1744 9661 6005 9682 4659]
 [   0    0    0 1388 1604 5026 7696 5895]
 [   0    0    0    0    0 2876 3682 5639]
 [9637 9352 3422 3682 5639 1294 4798 4959]]


In [16]:
### Feature representation
dim = 10
model = Sequential()
# Specify input_length so the model can be built and summary shows shapes
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=set_length))
model.compile(optimizer='adam', loss='mse')
# Explicitly build the model to populate the summary
model.build(input_shape=(None, set_length))

d:\Krish_Naik\venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 245ms/step


array([[[ 0.04362715, -0.04096677,  0.03586683, -0.01813827,
         -0.03247078, -0.00715358, -0.00080587,  0.00291798,
         -0.0277782 , -0.01921517],
        [ 0.04362715, -0.04096677,  0.03586683, -0.01813827,
         -0.03247078, -0.00715358, -0.00080587,  0.00291798,
         -0.0277782 , -0.01921517],
        [ 0.04362715, -0.04096677,  0.03586683, -0.01813827,
         -0.03247078, -0.00715358, -0.00080587,  0.00291798,
         -0.0277782 , -0.01921517],
        [ 0.04362715, -0.04096677,  0.03586683, -0.01813827,
         -0.03247078, -0.00715358, -0.00080587,  0.00291798,
         -0.0277782 , -0.01921517],
        [-0.02669284,  0.03961896,  0.00680869, -0.02869858,
          0.04918681,  0.02168903,  0.02669081,  0.03381992,
         -0.04668155, -0.01205702],
        [-0.04773704,  0.02714367, -0.03708476,  0.03061873,
          0.00930173,  0.00389392, -0.03610451,  0.00114683,
         -0.04638061, -0.00045934],
        [-0.01232745,  0.01662732,  0.02233602, -0.0